global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'discovered'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
        refresh_interval: 30s
